
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/doom/.local/share/JetBrains/Toolbox/apps/clion-nova/bin/cmake/linux/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.5.0-26-generic - x86_64
...
