name: CMake on ppc64le

on:
  workflow_dispatch:

jobs:
  build-linux-ppc64le:
    name: Build for Linux (ppc64le)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Enable Multiarch and Install Dependencies
        run: |
          sudo dpkg --add-architecture ppc64el
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential git cmake ninja-build \
            gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu binutils-powerpc64le-linux-gnu \
            libasound2-dev-powerpc64le-cross libpulse-dev-powerpc64le-cross libaudio-dev-powerpc64le-cross \
            libjack-dev-powerpc64le-cross libsndio-dev-powerpc64le-cross libx11-dev-powerpc64le-cross \
            libxext-dev-powerpc64le-cross libxrandr-dev-powerpc64le-cross libxcursor-dev-powerpc64le-cross \
            libxfixes-dev-powerpc64le-cross libxi-dev-powerpc64le-cross libxss-dev-powerpc64le-cross \
            libxkbcommon-dev-powerpc64le-cross libdrm-dev-powerpc64le-cross libgbm-dev-powerpc64le-cross \
            libgl1-mesa-dev-powerpc64le-cross libgles2-mesa-dev-powerpc64le-cross libegl1-mesa-dev-powerpc64le-cross \
            libdbus-1-dev-powerpc64le-cross libibus-1.0-dev-powerpc64le-cross libudev-dev-powerpc64le-cross \
            fcitx-libs-dev-powerpc64le-cross libpipewire-0.3-dev-powerpc64le-cross libwayland-dev-powerpc64le-cross \
            libdecor-0-dev-powerpc64le-cross liburing-dev-powerpc64le-cross libxtst-dev-powerpc64le-cross \
            gnome-desktop-testing-powerpc64le-cross
      - name: Configure
        run: cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=toolchain-ppc64le.cmake -DCMAKE_BUILD_TYPE=Release -S . -B build-ppc64le
      - name: Build
        run: cmake --build build-ppc64le --target 8ChocChip --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: 8ChocChip-Linux-ppc64le
          path: |
            build-ppc64le/Release/8ChocChip
            build-ppc64le/Release/*.so
            build-ppc64le/Release/assets/