name: CMake on ppc64le

on:
  workflow_dispatch:

jobs:
  build-linux-ppc64le:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            build-essential git cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev libpipewire-0.3-dev libwayland-dev libdecor-0-dev liburing-dev libxtst-dev


      - name: Configure
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PWD/toolchains/toolchain-ppc64le.cmake -S . -B build

      - name: Build
        run: cmake --build build --target 8ChocChip --config Release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: 8ChocChip-Linux-ppc64le
          path: |
            build/Release/8ChocChip*
            build/Release/*.so
            build/Release/assets/