name: CMake on ppc64le

on:
  workflow_dispatch:

jobs:
  build-linux-ppc64le:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends build-essential git cmake ninja-build \
            gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu pkg-config-powerpc64le-linux-gnu

      - name: Configure
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PWD/toolchains/toolchain-ppc64le.cmake -S . -B build

      - name: Build
        run: cmake --build build --target 8ChocChip --config Release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: 8ChocChip-Linux-ppc64le
          path: |
            build/Release/8ChocChip*
            build/Release/*.so
            build/Release/assets/